obj/./lib/cstring.o: lib/cstring.cpp include/lib/cstring.h
obj/./lib/cxxsupport.o: lib/cxxsupport.cpp include/common.h \
 include/kheap.h include/scio.h include/lib/cxxsupport.h
obj/./core/main.o: core/main.cpp include/multiboot.h include/scio.h \
 include/descriptor_table.h include/common.h include/port.h \
 include/page.h include/kheap.h include/task.h include/lib/cxxsupport.h \
 include/lib/cstring.h
obj/./core/page.o: core/page.cpp include/lib/cstring.h include/page.h \
 include/common.h include/multiboot.h include/scio.h \
 include/descriptor_table.h include/kheap.h
obj/./core/scio.o: core/scio.cpp include/common.h include/lib/stdarg.h \
 include/scio.h include/port.h include/lib/cstring.h include/lib/ctype.h
obj/./core/common.o: core/common.cpp include/common.h \
 include/lib/stdarg.h include/scio.h include/port.h
obj/./core/descriptor_table.o: core/descriptor_table.cpp \
 include/descriptor_table.h include/common.h include/lib/cstring.h \
 include/port.h include/scio.h
obj/./core/task.o: core/task.cpp include/task.h include/common.h \
 include/page.h include/scio.h include/lib/cstring.h
obj/./core/kheap.o: core/kheap.cpp include/lib/rbtree.h include/common.h \
 include/kheap.h include/page.h include/scio.h
obj/./core/asm/loader.o: ./core/asm/loader.s
obj/./core/asm/interrupt.o: ./core/asm/interrupt.s
